import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Container} from '@chakra-ui/react'
import axios from "axios"
import {useEffect, useState} from 'react';
import TableComponent from '../components/Table';

export default function Home() {

    // const [data, setData] = useState({})
    //
    // useEffect(() => {
    // }, [])
    //
    // const call = async () => {
    //     const url = ''
    //     const response = await axios.get(url)
    //     if (response) setData(response)
    // }

    return (

        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Container>
                    Hello World
                    <TableComponent/>
                </Container>
            </main>
        </div>

    )
}
